const CONFIG = {
  INFURA_API_KEY: "INFURA_API_KEY",
  PRIVATE_KEY: "PRIVATE_KEY",
  ETHERSCAN_API_KEY: "ETHERSCAN_API_KEY",
  TOKEN_REWARDS_ADDRESS: "TOKEN_REWARDS_ADDRESS",
};

module.exports = CONFIG;
